version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wise_wallet
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wise_wallet_dbs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # Define o volume nomeado para persistência